# Generated by Django 4.1.1 on 2022-09-23 22:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=16)),
                ('description', models.TextField()),
                ('services', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first', models.CharField(max_length=100)),
                ('last', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=16)),
                ('works_at', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.business')),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_email', models.CharField(max_length=50)),
                ('client_phone', models.CharField(max_length=16)),
                ('date', models.CharField(max_length=15)),
                ('start', models.CharField(max_length=5)),
                ('end', models.CharField(max_length=5)),
                ('business_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.business')),
                ('provider_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.employee')),
            ],
        ),
    ]
