# Generated by Django 4.1.1 on 2022-10-02 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_remove_address_zip_appointment_address_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='zip',
            field=models.IntegerField(default=None, max_length=5),
        ),
    ]
