# Generated by Django 4.1.1 on 2022-11-02 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_remove_business_password_newuser_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='client_name',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
