# Generated by Django 4.1.1 on 2022-11-03 22:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_appointment_client_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recovery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=None, max_length=6)),
                ('business_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='base.business')),
            ],
        ),
    ]
