# Generated by Django 4.1.1 on 2022-10-19 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_address_zip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='zip',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='business',
            name='password',
            field=models.CharField(max_length=64),
        ),
    ]
