# Generated by Django 4.1.1 on 2022-10-22 03:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_address_zip_alter_business_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='services',
        ),
        migrations.AddField(
            model_name='appointment',
            name='token',
            field=models.CharField(default=None, max_length=22),
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=50)),
                ('businessID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.business')),
            ],
        ),
    ]
