# Generated by Django 4.1.1 on 2022-11-03 23:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_recovery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recovery',
            name='business_id',
        ),
        migrations.AddField(
            model_name='recovery',
            name='owner_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
