# Generated by Django 4.1.1 on 2022-10-22 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_remove_business_services_appointment_token_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='service_list',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
