# Generated by Django 4.1.1 on 2022-11-12 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_remove_recovery_business_id_recovery_owner_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
