# Generated by Django 4.1.1 on 2022-10-22 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_business_service_list'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Services',
            new_name='Service',
        ),
        migrations.RenameField(
            model_name='business',
            old_name='service_list',
            new_name='services',
        ),
    ]
