# Generated by Django 4.1.1 on 2022-12-03 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_business_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='url',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='employee',
            name='url',
            field=models.TextField(default=''),
        ),
    ]
